#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba16f) uniform writeonly image2D normalMap;
layout(binding = 1, rg32f) uniform readonly image2D slopeMap;

void main() {
    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
    vec2 slope = imageLoad(slopeMap, texCoord).xy;

    vec3 normal = normalize(vec3(-slope.x, 1.0, -slope.y));

    imageStore(normalMap, texCoord, vec4(normal * 0.5 + 0.5, 1.0));
}
